go.mod, internal/pkg/registry/entry.go, internal/pkg/registry/entry_test.go, internal/pkg/registry/filesystem.go, internal/pkg/registry/filesystem_test.go, internal/pkg/registry/github.go, internal/pkg/registry/github_test.go, internal/pkg/registry/source.go, registry/apps/bash.yaml, registry/apps/explorer.yaml, registry/apps/powershell-admin.yaml, registry/apps/powershell.yaml, registry/apps/visualstudio.yaml, registry/apps/vscode-insiders.yaml, registry/apps/vscode.yaml, registry/apps/zsh.yaml, registry/services/azure-devops.yaml, registry/services/bitbucket.yaml, registry/services/github.yaml, registry/services/gitlab.yaml
This adds the initial configuration registry entries to the repository in preparation for addressing #17.
=> Add initial configuration registry entries

internal/pkg/repo/branches.go, internal/pkg/repo/branches_test.go, internal/pkg/tasks/gitcheckout.go, internal/pkg/tasks/gitcheckout_test.go
This PR improves the way that the `gt branch` functionality works, ensuring that more branch names are presented for auto-complete and that checking out those branches works the way one would expect.
=> Improve branch functionality

src/commands/complete.rs, src/commands/config.rs, src/commands/info.rs, src/commands/open.rs, src/core/config.rs
=> Make it possible to manage aliases using gt config

src/commands/update.rs, src/update/api.rs, src/update/github.rs, src/update/manager.rs
=> test: Mock GitHub endpoint for update tests

Cargo.lock, Cargo.toml, src/commands/update.rs, src/main.rs
=> fix: Correct an issue with the way that updates are triggered

src/commands/config.rs, src/core/config.rs
=> feat: Add a --force parameter to the config add command to overwrite existing entries

src/errors/keyring.rs
=> Don't report missing key-ring entries as a system error

Cargo.toml
=> ci: Build release artifacts with debug symbols

src/online/service/github.rs
=> fix: Don't return an error when attempting to create a GitHub repo which already exists

src/commands/branch.rs, src/commands/mod.rs, src/commands/switch.rs, src/git/mod.rs, src/git/switch.rs, src/tasks/git_switch.rs, src/tasks/mod.rs
Adds support for using the _git switch_ command which allows users to switch to a specified branch or create a new branch before switching to it.
=> feat: add support for git switch command

.github/actions-rs/grcov.yml, .github/workflows/rust-test.yml
This PR adds caching for Rust crates and build outputs between test runs to try and reduce the time taken to run tests.
=> ci: Add caching of Rust artifacts between test runs

src/commands/clone.rs, src/commands/setup.rs
This PR addresses some code style warnings. Nothing fancy.
=> style: Address some code warnings

src/commands/config.rs, src/commands/ignore.rs, src/core/config.rs, src/core/launcher.rs, src/core/resolver.rs, src/git/cmd.rs, src/online/registry/file_registry.rs, src/online/registry/github_registry.rs, src/tasks/new_folder.rs, src/tasks/write_file.rs, src/update/github.rs, src/update/manager.rs
This PR introduces bespoke error messages for all filesystem operations to help users make informed decisions about how to resolve problems.
=> feat: Rewrite all std::io filesystem error messages to improve their context (fixes #174)

src/core/config.rs, src/core/features.rs
This PR ensures that we correctly merge feature flags when loading config files.
=> fix: Ensure that we merge features from config files correctly

src/commands/update.rs
This PR filters releases based on their compatibility with your current platform. While this helps us handle any potential deprecations in future, the more important improvement is that we can now more effectively handle situations where a GitHub release is created but the artifacts have not yet been published for a specific platform.
=> feat: Exclude incompatible (or not yet built) updates from the list of available updates

src/errors/mod.rs
=> tweak: Improve error message advice

.github/workflows/release.yml, src/commands/complete.rs, src/commands/setup.rs, src/update/fs.rs, src/update/manager.rs
This PR resolves some code quality warnings from our GitHub Actions and Rust Vet
=> refactor: Cleanup code quality warnings

src/online/service/github.rs
This PR introduces limited support for retrying requests to GitHub in the face of retryable failures (including 429 and 5xx error responses, and transient network issues).
It should help reduce the likelihood of failure during network and service instability, especially when running commands like `gt new`.
=> feat: Add support for retrying failed requests to GitHub

src/online/service/github.rs
This PR improves the error reporting presented when calling GitHub fails - specifically the way in which HTTP 500 Internal Server Errors (which return non-JSON responses at times) are handled.
This should make it easier for users to self-triage these problems.
=> feat: Add improved error reporting for issues parsing GitHub responses

src/core/resolver.rs, src/fs/mod.rs
This PR does some work to make the resolver logic a bit more sensible, reducing code duplication and improving consistency in the way we access the filesystem to enumerate options.
=> refactor: Improve resolver implementation

Cargo.lock, Cargo.toml, docs/config/README.md, docs/config/features.md, docs/package-lock.json, src/engine/config.rs, src/engine/target.rs
docs(config): Document usage of environment vars in directory
additional fixes:
- formatting of features.md
- remove warning of deprecated `keep` in target.rs
=> feat(config): allow env vars in directory config
