SierraSoftworks/git-tool

README.md
Somewhat surprisingly, Azure DevOps doesn't use the `.git` extension convention for repository access over SSH.
=> Correct gitUrl for Azure DevOps

internal/pkg/di/output.go, internal/pkg/mocks/output.go
This should hopefully fix UTF-8 printing issues when using characters like `λ` (which currently appear as `?`).
=> refactor: Add support for the io.StringWriter to the output abstraction

.gitignore, internal/app/gitignore.go, internal/app/gitignore_test.go, internal/pkg/gitignore/file.go, internal/pkg/gitignore/file_test.go, internal/pkg/gitignore/header.go, internal/pkg/gitignore/header_test.go, test/data/ignore/oldgo.gitignore
This expands the `gt ignore` function to detect whether its output is being piped (`> .gitignore`) and if not, will write changes to the `.gitignore` file in the current directory.
`.gitignore` files managed by this tool will have a header injected which looks like the following:
```
```
Whenever this header is encountered, the listed `@languages` will be merged with the languages provided in `gt ignore lang1 lang2` and the content will be updated with the latest language ignore definitions.
=> Improve gitignore functionality

go.mod, go.sum, internal/app/app.go, internal/app/shell_init.go, internal/app/shell_init_test.go, internal/pkg/autocomplete/init.go, internal/pkg/autocomplete/init_test.go
=> Add shell-init command to simplify setup of shell integration

cmd/git-tool/main.go, internal/app/branch.go, internal/app/info.go, internal/app/info_test.go, internal/app/new.go, internal/app/new_test.go, internal/app/open.go, internal/app/open_test.go, internal/app/scratch.go, internal/app/update.go
When reporting errors to the user, we should differentiate between fatal and non-fatal errors and only focus on reporting fatal ones as "errors" while the remainder are advisories or cautions.
When an error like a "repository not found" is encountered, we should not treat that as a critical problem with the program.
=> Differentiate between critical and usage errors

internal/app/branch.go, internal/app/branch_test.go, internal/pkg/tasks/gitcheckout.go, internal/pkg/tasks/gitcheckout_test.go, internal/pkg/tasks/gitnewref.go
This PR fixes #24 by ensuring that if a remote branch with the same name already exists, it will be checked out.
=> Automatically checkout remote branches if they exist

src/main.rs
=> fix: Don't attempt to escape incoming command line arguments for legacy update flag

.github/workflows/rust-release.yml
=> ci: Switch to v2 of artifact tools (which ensures that the correct Cargo file is used for release builds)

.github/workflows/rust-release.yml, Cargo.toml
=> fix: Use Sentry symbolicator for debug info and return to release builds

Cargo.lock, Cargo.toml, src/core/launcher.rs, src/errors/mod.rs, src/errors/nix.rs, src/main.rs
=> fix: Prevent Git-Tool from intercepting signals intended for child processes

Cargo.toml, src/commands/switch.rs
Removes the short alias "_s_" for switch that conflicts with the alias for scratchpad.
=> fix: remove conflicting switch short alias

src/commands/clone.rs, src/commands/mod.rs
This PR introduces a `gt clone` command which will allow users to clone repositories into their dev directory without opening them, simplifying batch imports and automation.
=> feat: Add a `gt clone` command

src/core/launcher.rs, src/core/resolver.rs, src/errors/mod.rs, src/online/gitignore.rs, src/tasks/mod.rs
This PR changes the way in which we generate error messages to make it much clearer when a parent error is caused by a child, as well as combining the advice provided by each error in the hierarchy in a more logical manner.
The goal is to ensure that users can more easily understand the cause of a problem without us needing to rewrite every error message in the codebase.
In addition, we've made some small changes to the error messages returned by the resolver when you're in your dev directory, but not within a repository there.
> Oh no! Current directory ('G:\Programming\github.com\SierraSoftworks') is not a valid repository.
> Advice: Make sure that you are currently within a repository contained within your development directory ('\?\G:\Programming').
> 
> Oh no! The service …
=> Improve "not a valid repo" error messages when running `gt info`

Cargo.lock, Cargo.toml, src/commands/new.rs, src/commands/setup.rs, src/core/config.rs, src/core/features.rs, src/core/mod.rs, src/core/prompt.rs, src/errors/mod.rs, src/main.rs, src/online/service/github.rs, src/tasks/create_remote.rs, src/tasks/git_clone.rs, src/tasks/git_remote.rs, src/telemetry/mod.rs
This PR introduces a feature flag to control [Sentry](https://sentry.io) error reporting so that users can opt out of this behaviour if they wish.
Fixes #167
=> feat: Add the ability to opt out of Sentry error reporting and other telemetry

src/commands/config.rs, src/commands/setup.rs, src/core/config.rs, src/core/features.rs
This PR adds the ability to configure feature flags through the `gt config feature` sub-command.
Fixes #87
=> feat: Add the ability to control feature flags through the `gt config` CLI

src/core/config.rs
This PR fixes an issue with the way that config files were loaded, which would result in the default feature configuration being ignored.
=> fix: Correctly initialize the config file with the default features

src/commands/config.rs
This PR adds the ability to view the state of a config feature flag by running `gt config feature telemetry` without providing a new enable/disable state. It will print out `telemetry = true` (or the appropriate flag and its value).
=> feat: Print out information about a feature flag's current state if no state is provided

src/errors/mod.rs, src/update/github.rs, src/update/manager.rs
This PR expands the test suite to provide better coverage for the update workflow, helping ensure that we don't break anything there (since it's relatively complex).
=> test: Add tests for the update manager

README.md, src/commands/setup.rs, src/console/output.rs, src/core/config.rs, src/core/prompt.rs, src/main.rs
This PR, amongst other things, addresses some issues with the first-run experience for new users, documents some Windows dependencies, stops us reporting some user-level errors (Sentry hooking `error!()` by default) etc.
=> doc: Add information about the VC++ dependency on Windows

src/console/output.rs, src/errors/mod.rs, src/git/cmd.rs, src/git/mod.rs
Currently if a git command fails, Git-Tool will report it as a system error. This is almost always wrong, so let's report it as a user error for now and let people report issues themselves if they find any.
=> fix: Don't report Git errors as system-level errors

src/core/config.rs
=> fix: Update the default config to use the correct URLs for Azure DevOps

src/commands/open.rs, src/main.rs
=> fix: Move the helpful warning about missing a config file to the gt open command

docs/commands/repos.md, src/commands/mod.rs, src/commands/remove.rs
This PR introduces a new command (`gt remove`) which allows you to remove repositories from your local machine when you no longer need them.
=> feat: Add a command to remove repositories

src/commands/update.rs, src/update/github.rs, src/update/release.rs
This PR adds support for differentiating between pre-release and stable releases of Git-Tool when installing updates.
=> feat: Add support for updating to pre-release versions of Git-Tool

registry/apps/finder.yaml
This PR introduces a new `apps/finder` template which allows you to open the MacOS finder app in a repo using `gt o finder`.
To install it, you need to run `gt config add apps/finder`.
=> feat: Add a registry template for Mac OS finder

docs/config/templates.md, registry/services/azure-devops.yaml, src/core/config.rs, src/core/service.rs
This PR makes some changes to the default configuration, as well as the published Azure DevOps service in the registry, to ensure that repo names and namespaces are URL encoded (i.e. replace ` ` with `%20`) so that we can support repositories that have spaces in their names without needing to jump through ridiculous hoops.
```bash
> gt o "dev.azure.com/sierrasoftworks/example/test repo"
💣 💩
> gt o dev.azure.com/sierrasoftworks/example/test%20repo
✅ 🤮
```
```bash
> gt o "dev.azure.com/sierrasoftworks/example/test repo"
🌈
```
=> fix: Ensure that Azure DevOps paths are (by default) URL escaped to support spaces in repo names... 🤦

docs/commands/dev.md, src/commands/mod.rs, src/commands/prune.rs, src/console/mod.rs, src/console/prompt.rs, src/git/branch.rs, src/git/mod.rs, src/tasks/write_file.rs
This PR introduces a new `gt prune` command which allows you to quickly remove any local branch refs which have been merged. This is particularly useful if you use unique branches for PRs and want to clean out the cruft once your PRs are merged.
=> feat: Add a new `gt prune` command to remove local branches that have been merged already

docs/commands/repos.md, docs/config/features.md, src/commands/new.rs, src/core/features.rs, src/git/cmd.rs, src/online/service/github.rs, src/online/service/mod.rs, src/tasks/ensure_no_remote.rs, src/tasks/mod.rs
This PR adds a new `check_exists` feature flag which, when enabled and attempting to create a repository on a supported service, will first check whether the service has an existing repo with the same name.
=> feat: Add support for checking whether a repository exists before creating it

src/commands/config.rs, src/commands/doctor.rs, src/commands/setup.rs, src/core/builder.rs, src/core/config.rs, src/main.rs
This refactor is designed to greatly simplify first-time setup by chosing some reasonable default paths and allowing you to use Git-Tool without needing to create a custom config file and export the `GITTOOL_CONFIG` environment variable.
=> feat: Add support for loading Git-Tool's config from a default config path

.github/workflows/nix.yml, .gitignore, Cargo.lock, flake.lock, flake.nix, src/commands/config.rs, src/commands/setup.rs
This PR adds a Nix Flake for Git-Tool which can be installed on any of the supported platforms using the following command:
```bash
nix build github:SierraSoftworks/git-tool
```
This should make it relatively straightforward to bootstrap Git-Tool automatically using NixOS/home-manager if that's your thing.
=> feat: Add support for building Git-Tool using Nix

.github/workflows/test.yml, src/commands/config.rs, src/git/commit.rs, src/git/config.rs, src/git/mod.rs, src/tasks/git_clone.rs, src/tasks/git_init.rs
This PR adds native support to the test suite for configuring the `user.name` and `user.email` Git options on a per-repository basis (when generating and/or cloning temporary repositories for testing purposes). This removes the need to pre-configure the test environment and should resolve some of the failures we're seeing when running the Nix test suite in an uninitialized build environment.
=> test: Remove the need for pre-emptive git configuration

.github/workflows/nix.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, src/core/http.rs, src/git/cmd.rs, src/main.rs
This PR resolves the way in which we report the status of OpenTelemetry spans for web requests, ensuring that we don't inadvertently record "error" spans for successful requests.
=> fix: Resolve OpenTelemetry status reporting

src/commands/auth.rs, src/online/service/github.rs, src/online/service/mod.rs
This PR adds a message instructing the user on how to authenticate when running `gt auth <svc>`, simplifying initial bootstrapping.
=> feat: Add authentication instructions when running gt auth

Cargo.lock, Cargo.toml, src/commands/apps.rs, src/commands/auth.rs, src/commands/clone.rs, src/commands/complete.rs, src/commands/config.rs, src/commands/doctor.rs, src/commands/fix.rs, src/commands/ignore.rs, src/commands/info.rs, src/commands/list.rs, src/commands/mod.rs, src/commands/new.rs, src/commands/open.rs, src/commands/prune.rs, src/commands/remove.rs, src/commands/scratch.rs, src/commands/services.rs, src/commands/setup.rs, src/commands/shell_init.rs, src/commands/switch.rs, src/commands/update.rs, src/main.rs
This is a code refactor intended to simplify the introduction of new commands by centralizing registration through the `inventory` crate.
=> refactor: Switch to dynamically discovering commands

src/commands/scratch.rs, src/completion/completer.rs, src/core/resolver.rs
This PR introduces the ability to run commands like `gt scratch ~5` or `gt scratch ^2` to resolve the scratchpad from (respectively) 5 weeks ago or 2 weeks ago. This closes #1295
=> feat: Add support for resolving scratchpads relative to the current week

Cargo.toml, docs/.vuepress/components/Releases.vue, docs/commands/scratch.md, docs/package-lock.json, flake.nix, src/commands/mod.rs, src/commands/temp.rs, src/core/mod.rs, src/core/resolver.rs, src/core/target.rs, src/core/templates.rs
This pull request adds a new `gt temp` command to create a temporary directory which will be automatically deleted when the active process terminates. It's particularly useful for playing with something you don't intend on keeping (such as testing out a language feature).
```bash
gt temp
gt temp pwsh
gt temp --keep
```
=> feat: Add a `gt temp` command to create a temporary directory

docs/commands/repos.md, docs/package-lock.json, src/commands/clone.rs
This PR adds a new `gt clone @file` command which allows you to import a list of repositories from a file, simplifying migration from one machine to another.
The workflow would involve something like the following:
```
gt list -q > repos.txt
gt clone @repos.txt
```
=> feat: Add support for importing a file list of repos

src/commands/clone.rs, src/commands/complete.rs, src/commands/new.rs, src/commands/open.rs, src/commands/prune.rs, src/core/templates.rs, src/git/add.rs, src/git/branch.rs, src/git/checkout.rs, src/git/clone.rs, src/git/cmd.rs, src/git/commit.rs, src/git/config.rs, src/git/fetch.rs, src/git/init.rs, src/git/refs.rs, src/git/remote.rs, src/git/switch.rs, src/tasks/git_add.rs, src/tasks/git_checkout.rs, src/tasks/git_commit.rs, src/tasks/git_remote.rs, src/tasks/write_file.rs
This PR adds logic to explicitly check the existence of a git repo directory before spawning a git command in said directory, allowing us to present better error messages to the user in these situations (instead of a generic `File not found (error code 2)` error).
=> feat: Improve handling of missing git repo directory

docs/commands/repos.md, src/commands/mod.rs, src/commands/rename.rs, src/core/target.rs, src/git/cmd.rs, src/git/mod.rs, src/git/remote.rs, src/tasks/git_move_upstream.rs, src/tasks/mod.rs, src/tasks/move_directory.rs
this PR adds the functionality to rename git repositories and automatically change the upstream URL.
For example, given a repository layout of
```
~/
└ src/
└ gh/
└ SierraSoftworks/
└ git-tool (origin git@github.com:SierraSoftworks/git-tool.git)
```
running
```bash
gt mv gh:SierraSoftworks/git-tool gh:SierraSoftworks/gt
```
will result in
```
~/
└ src/
└ gh/
└ SierraSoftworks/
└ gt (origin git@github.com:SierraSoftworks/gt.git)
```
However, if you wish to only update the repository locally, you can specify `--no-update-remote`:
```bash
gt mv gh:SierraSoftworks/git-tool gh:SierraSoftworks/gt
```
will result in
```
~/
└ src/
└ gh/
└ SierraSoftworks/
└ gt (origin git@github.com:SierraSoftworks/git-tool.git)
```
leaving the `origin` URL in tact
=> add new command to easily rename a git-repository
